# Bienvenidos

Esto es un notebook. Podemos escribir en lenguaje Markdown, el cual nos permite:
* Listas
* Escribir en **negrita** y *cursiva*
* Más información aquí: [Markdown-Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

### PREGUNTAD!!

Sobretodo si os perdeis, no lleguemos a casos donde no sepais que estamos haciendo.

![Imagen no cargada. Edita y borra la @ ](https://memegenerator.net/img/instances/28913469.jpg)

# Introducción

![ ](diagrama_resumen.png )

# Bibliografía 

Sobre **estadística**: [Practical Statistics for Data Scientists: 50 Essential Concepts](https://www.amazon.com/Practical-Statistics-Data-Scientists-Essential/dp/1491952962/ref=sr_1_3?ie=UTF8&qid=1518719786)


Sobre **R**: [R for Data Science: Import, Tidy, Transform, Visualize, and Model Data](https://www.amazon.com/Data-Science-Transform-Visualize-Model/dp/1491910399/ref=sr_1_1?ie=UTF8&qid=1518791084) Este libro es bastante completo, abarca mucho temario que no veremos por falta de tiempo.
                    


## Estadística vs Machine Learning


Más información aquí: [Markdown-Cheatsheet](https://www.reddit.com/r/MachineLearningLounge/comments/9soaw4/let_me_fix_that_for_you/)


* Estadística: Trata de entender las variables y su relación entre ellas. Las estadísitcas te ayudan a entender como es tu población de datos.

* Machine Learning: Trata de hacer predicciones, crear modelos que, a partir de una población limitada puedan **generalizar** y aprender como se comportarán los datos.



# Introducción a R

R es un lenguaje de programación orientado a la estadística.

Algo parecido a SPSS o Matlab.

Es código abierto y se entrega bajo licencia GPL (versión 2 o posterior). Además existen multitud de paquetes que complementan su funcionalidad.

## Asignaciones

Podemos usar <- o el símbolo = para asignar un valor a una variable

In [12]:
print('Hola mundo!!!')

[1] "Hola mundo!!!"


In [8]:
a = 8
print(a)

[1] 8


In [18]:
b <- 3
print(b)

[1] 3


In [14]:
7 -> c
print(c)

[1] 7


## Operaciones

In [20]:
a+b #Suma

[1] 11

In [22]:
a^b

[1] 512

In [23]:
a %% b

[1] 2

In [24]:
a / b

[1] 2.666667

In [25]:
a - b 

[1] 5

In [26]:
a+b #Suma

a^b #potencia

a %% b #módulo

a / b #División

a - b #Resta

[1] 11

[1] 512

[1] 2

[1] 2.666667

[1] 5

## Funciones básicas

Las funciones 
 * siempre acaban en ()
 * pueden recibir un número variable de parámetros
 * pueden existir parámetros por defecto

Ver las variables en memoria, función ls()

In [27]:
ls()

[1] "a" "b" "c"

Ver el tipo de variable, función typeof(x):

In [28]:
typeof(a)

[1] "double"

# Tipos de datos

## double

In [29]:
a <- 2022
a
typeof(a)

[1] 2022

[1] "double"

In [30]:
b <- exp(1)
b
typeof(b)

[1] 2.718282

[1] "double"

In [31]:
?exp

## integer

In [32]:
ai <- as.integer(3.784)
ai
typeof(ai)

[1] 3

[1] "integer"

## Diferencias entre  integer y double

El número más grande que podemos representar es diferente:

In [33]:
.Machine$integer.max
.Machine$double.xmax

[1] 2147483647

[1] 1.797693e+308

El tamaño que ocupan en memoria es:

In [34]:
object.size(ai)
object.size(b)

56 bytes

56 bytes

## character

In [38]:
s1 <- "Paquita"
s1
typeof(s1)

[1] "Paquita"

[1] "character"

Las cadenas de texto se pueden concatenar usando la función paste(x,y,z...)

In [39]:
?paste

In [42]:
paste(s1, "Salas","Cuarta temporada", sep="---")

[1] "Paquita---Salas---Cuarta temporada"

## Logical

In [43]:
b1 <- TRUE
b2 <- T
b3 <- FALSE
paste("El valor de b1 es",b1)
paste("El valor de b2 es",b2)
paste("El valor de b3 es",b3)

[1] "El valor de b1 es TRUE"

[1] "El valor de b2 es TRUE"

[1] "El valor de b3 es FALSE"

Operaciones lógicas:


| A | B |AND|OR |XOR|NOT(A)|
|---|---|---|---|---|------|
| 0 | 0 | 0 | 0 | 0 |  1   |
| 0 | 1 | 0 | 1 | 1 |  1   |
| 1 | 0 | 0 | 1 | 1 |  0   |
| 1 | 1 | 1 | 1 | 0 |  0   |

In [44]:
print(paste("b1 AND b3:",b1 & b3))
print(paste("b1 OR  b3:",b1 | b3))
print(paste("b1 XOR b3:",xor(b1 ,b3)))
print(paste("   NOT b1:",!b1))

[1] "b1 AND b3: FALSE"
[1] "b1 OR  b3: TRUE"
[1] "b1 XOR b3: TRUE"
[1] "   NOT b1: FALSE"


## Vectores

Los vectores se crean con la función c(), todos los elementos de un vector son del mimo tipo. Es decir, no se podrían mezclar caracteres y double.

En python:

   a = [1,2,3,40]
   
En R:

   a = c(1,2,3,40)

In [45]:
alturas<-c(1.80,1.60,1.50,1.90,1.75,1.63,1.65)
print(paste("alturas es una variable de tipo:",typeof(alturas)))

[1] "alturas es una variable de tipo: double"


In [46]:
print("Podemos ver la estructura de un objeto con la función str():")
str(alturas)

[1] "Podemos ver la estructura de un objeto con la función str():"
 num [1:7] 1.8 1.6 1.5 1.9 1.75 1.63 1.65


In [48]:
otroVector <- c("uno",2.0,"tres","14.0")
otroVector

[1] "uno"  "2"    "tres" "14.0"

In [49]:
str(otroVector)

 chr [1:4] "uno" "2" "tres" "14.0"


In [50]:
typeof(otroVector)

[1] "character"

### Acceso a elementos

In [51]:
print(paste("El valor del tercer elemento es:",alturas[3]))

[1] "El valor del tercer elemento es: 1.5"


**¡¡En R los arrays empiezan en 1!!**
![Imagen no cargada. Edita y borra la @ ](https://i.redd.it/iwnqgrrbls5z.png  )

Podemos dar nombres a cada elemento

In [52]:
myVector <- c(nombre="Philip",apellido="García",teléfono=600100100)

In [53]:
myVector

nombre    apellido    teléfono 
   "Philip"    "García" "600100100"

In [55]:
myVector["apellido"]

apellido 
"García"

In [56]:
myVector[2]

apellido 
"García"

In [57]:
myVector["teléfono"]

teléfono 
"600100100"

In [58]:
#Los nombres de una variable se pueden ver con la función names()
names(myVector)

[1] "nombre"   "apellido" "teléfono"

In [59]:
names(myVector) <- c("nombre_actualizado","apellido_actualizado", "telefono_actualizado")

In [60]:
myVector

nombre_actualizado apellido_actualizado telefono_actualizado 
            "Philip"             "García"          "600100100"

In [61]:
names(myVector)

[1] "nombre_actualizado"   "apellido_actualizado" "telefono_actualizado"

### Operaciones con vectores

Al operar contra una variable se aplica esa operación a todos los elementos del vector

In [62]:
metro2pie <- 3.28084
alturasEnPies <- alturas*metro2pie
alturasEnPies

[1] 5.905512 5.249344 4.921260 6.233596 5.741470 5.347769 5.413386

Si se opera con dos vectores de la misma longitud se aplica elemento a elemento.

In [63]:
alturas

[1] 1.80 1.60 1.50 1.90 1.75 1.63 1.65

In [64]:
alturaDeLosZapatos<-c(2,0,1,3,5,7,0)/100
alturaReal<-alturas - alturaDeLosZapatos
alturaReal

[1] 1.78 1.60 1.49 1.87 1.70 1.56 1.65

Se puede operar con vectores de tamaños diferentes, en este caso el vector más pequeño se replica

In [65]:
alturas * c(1,0)

Warning message in alturas * c(1, 0):
“longer object length is not a multiple of shorter object length”


[1] 1.80 0.00 1.50 0.00 1.75 0.00 1.65

1.8 1.6  1.5  1.9  1.75 1.63 1.65  XXX

1   0    1    0    1    0    1      0

In [68]:
alturas[1:6] * c(1,0)

[1] 1.80 0.00 1.50 0.00 1.75 0.00

Concatenar vectores

In [70]:
otras_alturas <-c(alturas,2,1.8,17)
otras_alturas

[1]  1.80  1.60  1.50  1.90  1.75  1.63  1.65  2.00  1.80 17.00

Longitud de un vector se obtiene con la función length()

In [71]:
length(alturas)

[1] 7

La estructura de la variable se puede ver con la función str()

In [72]:
str(alturas)

 num [1:7] 1.8 1.6 1.5 1.9 1.75 1.63 1.65


In [76]:
alturas[18] <- 1.9

In [77]:
alturas

[1] 1.80 1.60 1.50 1.90 1.75 1.63 1.65   NA   NA   NA   NA   NA   NA   NA   NA
[16]   NA   NA 1.90

In [83]:
length(alturas)

[1] 18

## Listas

Las listas se pueden considerar como vectores que pueden almacenar cualquier tipo de dato.

In [84]:
c(1,3,"catorce","panama")

[1] "1"       "3"       "catorce" "panama"

In [85]:
myList <- list(1,3,"catorce","panama")
str(myList)

List of 4
 $ : num 1
 $ : num 3
 $ : chr "catorce"
 $ : chr "panama"


In [86]:
myList

[[1]]
[1] 1

[[2]]
[1] 3

[[3]]
[1] "catorce"

[[4]]
[1] "panama"

Podemos asignar un nombre a cada valor

In [87]:
datosPersonales<-list(nombre="Philip",
                   apellido="García",
                   teléfono=600100100)
datosPersonales

$nombre
[1] "Philip"

$apellido
[1] "García"

$teléfono
[1] 600100100

### Acceso a elementos

Podemos acceder a los distintos elementos utilizando su índice o nombre:

In [90]:
datosPersonales[[1]]

[1] "Philip"

In [91]:
datosPersonales[["nombre"]]

[1] "Philip"

In [92]:
datosPersonales$nombre

[1] "Philip"

In [97]:
is.null(datosPersonales[["edad"]])

[1] TRUE

In [98]:
is.null(datosPersonales[["direccion"]])

[1] TRUE

In [99]:
names(datosPersonales)

[1] "nombre"   "apellido" "teléfono"

In [100]:
datosPersonales[["direccion"]] <- list(ciudad="Madrid",calle="Desengaño",numero=21)
datosPersonales[["direccion"]]

$ciudad
[1] "Madrid"

$calle
[1] "Desengaño"

$numero
[1] 21

In [101]:
datosPersonales

$nombre
[1] "Philip"

$apellido
[1] "García"

$teléfono
[1] 600100100

$direccion
$direccion$ciudad
[1] "Madrid"

$direccion$calle
[1] "Desengaño"

$direccion$numero
[1] 21

In [102]:
datosPersonales[["direccion"]]$calle

[1] "Desengaño"

In [103]:
datosPersonales[["direccion"]][["calle"]]

[1] "Desengaño"

In [104]:
datosPersonales$direccion[[2]]

[1] "Desengaño"

In [105]:
print(paste("La longitud total de la lista es",length(datosPersonales)))

[1] "La longitud total de la lista es 4"


## Factores

En estadística tenemos fundamentalmente dos tipos de variables:

* **Numéricas:** Estos datos tienen significado como medidas, por ejemplo la altura, peso, presión sanguinea, número de mascotas.
* **Categóricas:** Estos representan una característica, por ejemplo el género, color, sabores, ciudad.

Los factores son útiles cuando trabajamos con **variables categóricas**. Ej: Población de origen, colores, sabores

In [108]:
saboresDePlatos<-c("Dulce","Salado","Ácido","Amargo","Umami","Dulce","Salado","Ácido","Umami","Umami","Salado")
summary(saboresDePlatos)

   Length     Class      Mode 
       11 character character 

In [109]:
saboresDePlatosFactor <- factor(saboresDePlatos)
summary(saboresDePlatosFactor)

Ácido Amargo  Dulce Salado  Umami 
     2      1      2      3      3

In [110]:
str(saboresDePlatos)

 chr [1:11] "Dulce" "Salado" "Ácido" "Amargo" "Umami" "Dulce" "Salado" ...


In [111]:
str(saboresDePlatosFactor)

 Factor w/ 5 levels "Ácido","Amargo",..: 3 4 1 2 5 3 4 1 5 5 ...


In [112]:
saboresDePlatosFactor

[1] Dulce  Salado Ácido  Amargo Umami  Dulce  Salado Ácido  Umami  Umami 
[11] Salado
Levels: Ácido Amargo Dulce Salado Umami

In [113]:
print("Los factores internamente se gestionan como enteros")
as.numeric(saboresDePlatosFactor)

[1] "Los factores internamente se gestionan como enteros"


[1] 3 4 1 2 5 3 4 1 5 5 4

In [114]:
paste("sabor:",levels(saboresDePlatosFactor))

[1] "sabor: Ácido"  "sabor: Amargo" "sabor: Dulce"  "sabor: Salado"
[5] "sabor: Umami"

In [119]:
paste("sabor",levels(saboresDePlatosFactor),sep="--")

[1] "sabor--Ácido"  "sabor--Amargo" "sabor--Dulce"  "sabor--Salado"
[5] "sabor--Umami"

In [116]:
paste(levels(saboresDePlatosFactor),collapse=",")

[1] "Ácido,Amargo,Dulce,Salado,Umami"

In [121]:
cat(paste("Podemos ver los niveles con el comando levels:",
            paste(levels(saboresDePlatosFactor),collapse=",")))

Podemos ver los niveles con el comando levels: Ácido,Amargo,Dulce,Salado,Umami

In [128]:
factor(c(1,0,0,1,0,1),labels=c("NO","SI"))

[1] SI NO NO SI NO SI
Levels: NO SI

In [123]:
factor(c(10,5,5,0,5,0),labels=c("BAJO","MEDIO","ALTO"))

[1] ALTO  MEDIO MEDIO BAJO  MEDIO BAJO 
Levels: BAJO MEDIO ALTO

# Matrices

Podemos crear matrices con la función matrix. Como parámetros de entrada recibe un vector y el número de columnas (*ncol*) o filas (nrow). Un parámetro opcional (*byrow*) indica si la matriz se va a rellenar por filas o por columnas (valor por defecto)

In [129]:
1:12

[1]  1  2  3  4  5  6  7  8  9 10 11 12

In [133]:
m1<-matrix(c(1:12),ncol=3)
m1

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

In [134]:
?matrix

In [135]:
m2<-matrix(c(1:12),ncol=3,byrow=T)
m2

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

La dimensión del array se puede ver con la función *dim()* o con *str()*

In [136]:
dim(m1)

[1] 4 3

In [137]:
length(m1)

[1] 12

In [138]:
str(m2)

 int [1:4, 1:3] 1 4 7 10 2 5 8 11 3 6 ...


### Acceso

El acceso se realiza igual que los vectores, pero aquí tenemos dos dimensiones.

In [140]:
m1[1,3]

[1] 9

In [142]:
m1[,2]

[1] 5 6 7 8

También podemos dar nombres a las filas y columnas para luego poder acceder utilizando el nombre

In [ ]:
?paste0

In [143]:
paste0("row",1:4)

[1] "row1" "row2" "row3" "row4"

In [144]:
colnames(m1)<-paste0("col",1:3)
rownames(m1)<-paste0("row",1:4)
m1

col1 col2 col3
row1 1    5     9  
row2 2    6    10  
row3 3    7    11  
row4 4    8    12

In [145]:
paste("El valor de 'row1' y 'col3' es:",m1["row1","col3"])

[1] "El valor de 'row1' y 'col3' es: 9"

In [147]:
m1["row1",]

col1 col2 col3 
   1    5    9

Las funciones *colnames* y *rownames* 

In [149]:
colnames(m1)

[1] "col1" "col2" "col3"

### Operaciones con matrices 
#### Álgebra lineal básica

In [150]:
m1

col1 col2 col3
row1 1    5     9  
row2 2    6    10  
row3 3    7    11  
row4 4    8    12

Transpuesta

In [151]:
t(m1)

row1 row2 row3 row4
col1 1     2    3    4  
col2 5     6    7    8  
col3 9    10   11   12

Suma de constante

In [152]:
m1+10

col1 col2 col3
row1 11   15   19  
row2 12   16   20  
row3 13   17   21  
row4 14   18   22

Suma de matrices

In [153]:
m1+m2

col1 col2 col3
row1  2    7   12  
row2  6   11   16  
row3 10   15   20  
row4 14   19   24

Multiplicación de matrices

In [155]:
m1 %*% matrix(rep(1,12),nrow=3)

[,1] [,2] [,3] [,4]
row1 15   15   15   15  
row2 18   18   18   18  
row3 21   21   21   21  
row4 24   24   24   24

In [158]:
rep("a",5)

[1] "a" "a" "a" "a" "a"

Submatrices

In [159]:
m1[2:4,2:3]

col2 col3
row2 6    10  
row3 7    11  
row4 8    12

In [160]:
m1[c(3,2,4),2:3]

col2 col3
row3 7    11  
row2 6    10  
row4 8    12

# Tablas

Se utilizan para estudios de frecuencia. Cuentan el número de veces que ha ocurrido algo.

In [161]:
saboresDePlatos

[1] "Dulce"  "Salado" "Ácido"  "Amargo" "Umami"  "Dulce"  "Salado" "Ácido" 
 [9] "Umami"  "Umami"  "Salado"

In [163]:
tblSabores <- table(saboresDePlatos)
tblSabores

saboresDePlatos
 Ácido Amargo  Dulce Salado  Umami 
     2      1      2      3      3 

In [164]:
names(tblSabores)

[1] "Ácido"  "Amargo" "Dulce"  "Salado" "Umami"

In [165]:
str(tblSabores)

 'table' int [1:5(1d)] 2 1 2 3 3
 - attr(*, "dimnames")=List of 1
  ..$ saboresDePlatos: chr [1:5] "Ácido" "Amargo" "Dulce" "Salado" ...


Los atributos son una lista de propiedades asociadas a un objeto en R

In [166]:
attributes(tblSabores)

$dim
[1] 5

$dimnames
$dimnames$saboresDePlatos
[1] "Ácido"  "Amargo" "Dulce"  "Salado" "Umami" 


$class
[1] "table"

In [167]:
class(tblSabores)

[1] "table"

In [168]:
attributes(tblSabores)$dimnames$saboresDePlatos 

[1] "Ácido"  "Amargo" "Dulce"  "Salado" "Umami"

In [169]:
color  <- c("marrón","negro","blanco","negro","blanco","negro","negro","marrón","marrón","marrón")
animal <- c("gato","gato","perro","gato","gato","perro","perro","perro","gato","gato")

tbl_animal<-table(animal,color)
tbl_animal

       color
animal  blanco marrón negro
  gato       1      3     2
  perro      1      1     2

In [170]:
str(tbl_animal)

 'table' int [1:2, 1:3] 1 1 3 1 2 2
 - attr(*, "dimnames")=List of 2
  ..$ animal: chr [1:2] "gato" "perro"
  ..$ color : chr [1:3] "blanco" "marrón" "negro"


In [171]:
attributes(tbl_animal)$dimnames

$animal
[1] "gato"  "perro"

$color
[1] "blanco" "marrón" "negro"

In [172]:
attributes(tbl_animal)

$dim
[1] 2 3

$dimnames
$dimnames$animal
[1] "gato"  "perro"

$dimnames$color
[1] "blanco" "marrón" "negro" 


$class
[1] "table"

## Miniresumen parcial

Vector

In [175]:
vector_pesos <- c(5,7,8,9,10)
vector_pesos[c(2:3,5,14)]

[1]  7  8 10 NA

In [176]:
length(vector_pesos)

[1] 5

Listas

In [177]:
lista_medidas <- list(altura=1.5, ancho=1, peso = 3, unidades_peso="Kg", unidades_medida="m", 
                      fabricacion=list(numeroserie="A1238656", origen="Zamora"))
lista_medidas

$altura
[1] 1.5

$ancho
[1] 1

$peso
[1] 3

$unidades_peso
[1] "Kg"

$unidades_medida
[1] "m"

$fabricacion
$fabricacion$numeroserie
[1] "A1238656"

$fabricacion$origen
[1] "Zamora"

In [178]:
lista_medidas[["altura"]]

[1] 1.5

In [182]:
lista_medidas[[6]]

$numeroserie
[1] "A1238656"

$origen
[1] "Zamora"

In [183]:
lista_medidas[2:3]

$ancho
[1] 1

$peso
[1] 3

In [184]:
lista_medidas[2:3]$ancho

[1] 1

## Data Frame

Un Dataframe es una tabla como la que podemos encontrar en cualquier hoja de calculo.

![](pics/ejemplo_dataframe.png)

La información se estructura en columnas, cada columna puede ser de un tipo de variable diferente: categorica, numerica, fecha, etc..

Cada fila representa un elemento u objeto cuyos atributos están representados por las columnas.

En R se definen como un conjunto de vectores de la misma longitud. Cada vector puede ser de un tipo diferente.

In [185]:
plt <- c("Bollo","Palomitas","Limón","Ginebra","Noodles","Caramelo","Patatas fritas","Naranja","Ternera","Cerdo","Sopa")
cal <-c(150,200,10,20,200,5,500,15,450,460,30)

In [186]:
idx<- 5 
paste("Elemento",idx,":",plt[idx],"-",cal[idx],"cal")

[1] "Elemento 5 : Noodles - 200 cal"

In [188]:
comidas <- data.frame(plato=plt, calorias=cal, sabor=saboresDePlatos, stringsAsFactors = F)
comidas

plato          calorias sabor 
1  Bollo          150      Dulce 
2  Palomitas      200      Salado
3  Limón           10      Ácido 
4  Ginebra         20      Amargo
5  Noodles        200      Umami 
6  Caramelo         5      Dulce 
7  Patatas fritas 500      Salado
8  Naranja         15      Ácido 
9  Ternera        450      Umami 
10 Cerdo          460      Umami 
11 Sopa            30      Salado

In [189]:
str(comidas)

'data.frame':	11 obs. of  3 variables:
 $ plato   : chr  "Bollo" "Palomitas" "Limón" "Ginebra" ...
 $ calorias: num  150 200 10 20 200 5 500 15 450 460 ...
 $ sabor   : chr  "Dulce" "Salado" "Ácido" "Amargo" ...


### Acceso a elementos de un data frame

Acceso por filas:

In [195]:
comidas[2:3,]

plato     calorias sabor 
2 Palomitas 200      Salado
3 Limón      10      Ácido

In [196]:
comidas[c(-1,-3,-5,-10,-11),]

plato          calorias sabor 
2 Palomitas      200      Salado
4 Ginebra         20      Amargo
6 Caramelo         5      Dulce 
7 Patatas fritas 500      Salado
8 Naranja         15      Ácido 
9 Ternera        450      Umami

Acceso por columnas:

In [198]:
comidas[,c("plato","calorias")]

plato          calorias
1  Bollo          150     
2  Palomitas      200     
3  Limón           10     
4  Ginebra         20     
5  Noodles        200     
6  Caramelo         5     
7  Patatas fritas 500     
8  Naranja         15     
9  Ternera        450     
10 Cerdo          460     
11 Sopa            30

Se puede usar el símbolo **$** para acceder a una columna.  
Las siguientes dos llamadas son equivalentes:

In [199]:
comidas$plato

[1] "Bollo"          "Palomitas"      "Limón"          "Ginebra"       
 [5] "Noodles"        "Caramelo"       "Patatas fritas" "Naranja"       
 [9] "Ternera"        "Cerdo"          "Sopa"

In [200]:
comidas[,"plato"]

[1] "Bollo"          "Palomitas"      "Limón"          "Ginebra"       
 [5] "Noodles"        "Caramelo"       "Patatas fritas" "Naranja"       
 [9] "Ternera"        "Cerdo"          "Sopa"

In [201]:
comidas[,1]

[1] "Bollo"          "Palomitas"      "Limón"          "Ginebra"       
 [5] "Noodles"        "Caramelo"       "Patatas fritas" "Naranja"       
 [9] "Ternera"        "Cerdo"          "Sopa"

In [202]:
comidas[,c(-1,-2)]

[1] "Dulce"  "Salado" "Ácido"  "Amargo" "Umami"  "Dulce"  "Salado" "Ácido" 
 [9] "Umami"  "Umami"  "Salado"

In [203]:
comidas$plato[2:3]

[1] "Palomitas" "Limón"

In [204]:
comidas[2:3,"plato"]

[1] "Palomitas" "Limón"

In [205]:
colnames(comidas)

[1] "plato"    "calorias" "sabor"

Número de filas que tiene un dataframe:

In [206]:
nrow(comidas)

[1] 11

In [208]:
# El número de columnas es:
ncol(comidas)

[1] 3

También podemos dar nombres a las filas

In [209]:
rownames(comidas) <- paste0("comida",1:nrow(comidas))
comidas

plato          calorias sabor 
comida1  Bollo          150      Dulce 
comida2  Palomitas      200      Salado
comida3  Limón           10      Ácido 
comida4  Ginebra         20      Amargo
comida5  Noodles        200      Umami 
comida6  Caramelo         5      Dulce 
comida7  Patatas fritas 500      Salado
comida8  Naranja         15      Ácido 
comida9  Ternera        450      Umami 
comida10 Cerdo          460      Umami 
comida11 Sopa            30      Salado

In [210]:
comidas["comida5","calorias"]

[1] 200

In [211]:
comidas[5,"calorias"]

[1] 200

In [212]:
comidas[c(4,2),c(3,2,1)]

sabor  calorias plato    
comida4 Amargo  20      Ginebra  
comida2 Salado 200      Palomitas

El nombre de las columnas y de las filas se puede obtener y modificar con las funciones **colnames()** y **rownames()**.

In [213]:
colnames(comidas)
rownames(comidas)

[1] "plato"    "calorias" "sabor"

[1] "comida1"  "comida2"  "comida3"  "comida4"  "comida5"  "comida6" 
 [7] "comida7"  "comida8"  "comida9"  "comida10" "comida11"

### Dataset con variable categoricas 

In [216]:
comidas<-data.frame(plato=plt, calorias=cal, sabor=saboresDePlatos, stringsAsFactors = F)
comidas$plato <- as.factor(comidas$plato)
comidas$sabor <- as.factor(comidas$sabor)
str(comidas)

'data.frame':	11 obs. of  3 variables:
 $ plato   : Factor w/ 11 levels "Bollo","Caramelo",..: 1 8 5 4 7 2 9 6 11 3 ...
 $ calorias: num  150 200 10 20 200 5 500 15 450 460 ...
 $ sabor   : Factor w/ 5 levels "Ácido","Amargo",..: 3 4 1 2 5 3 4 1 5 5 ...


In [214]:
comidas<-data.frame(plato=plt, calorias=cal, sabor=saboresDePlatos, stringsAsFactors = T)
comidas
str(comidas)

plato          calorias sabor 
1  Bollo          150      Dulce 
2  Palomitas      200      Salado
3  Limón           10      Ácido 
4  Ginebra         20      Amargo
5  Noodles        200      Umami 
6  Caramelo         5      Dulce 
7  Patatas fritas 500      Salado
8  Naranja         15      Ácido 
9  Ternera        450      Umami 
10 Cerdo          460      Umami 
11 Sopa            30      Salado

'data.frame':	11 obs. of  3 variables:
 $ plato   : Factor w/ 11 levels "Bollo","Caramelo",..: 1 8 5 4 7 2 9 6 11 3 ...
 $ calorias: num  150 200 10 20 200 5 500 15 450 460 ...
 $ sabor   : Factor w/ 5 levels "Ácido","Amargo",..: 3 4 1 2 5 3 4 1 5 5 ...


## Arrays 3D

Se pueden crear arrays N-dimensionales con la función array

In [217]:
arr<-array(1:12,dim = c(3,2,2))
arr

, , 1

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6

, , 2

     [,1] [,2]
[1,]    7   10
[2,]    8   11
[3,]    9   12

El acceso a elementos es similar al de las matrices

In [218]:
arr[1,2,1]

[1] 4

In [219]:
arr[1,,]

[,1] [,2]
[1,] 1     7  
[2,] 4    10

In [220]:
arr[2,,]

[,1] [,2]
[1,] 2     8  
[2,] 5    11

In [221]:
arr[3,,]

[,1] [,2]
[1,] 3     9  
[2,] 6    12

In [222]:
arr[4,,]

ERROR: Error in arr[4, , ]: subscript out of bounds


In [223]:
arr[,2,]

[,1] [,2]
[1,] 4    10  
[2,] 5    11  
[3,] 6    12

## Fechas

Existen dos objetos para almacenar fechas en R.

* Posixct es recubrimiento sobre un timestamp en segundos.
* Posixlt es una lista de objetos que contiene la información de la fecha

In [227]:
d1<-as.POSIXct("2018-10-5 15:40", tz='CET')
d1

[1] "2018-10-05 15:40:00 CEST"

In [225]:
d2<-as.POSIXct("5/10/2018 17:33",format="%m/%d/%Y")

d2

[1] "2018-05-10 UTC"

In [226]:
?as.POSIXct

In [228]:
str(d1)

 POSIXct[1:1], format: "2018-10-05 15:40:00"


In [229]:
class(d1)

[1] "POSIXct" "POSIXt"

In [230]:
unclass(d1)

[1] 1538746800
attr(,"tzone")
[1] "CET"

In [231]:
d1+60*60*24

[1] "2018-10-06 15:40:00 CEST"

In [232]:
d3<-as.POSIXlt("2018-4-5")
d3

[1] "2018-04-05 UTC"

In [235]:
class(d3)

[1] "POSIXlt" "POSIXt"

In [238]:
unclass(d3)

$sec
[1] 0

$min
[1] 0

$hour
[1] 0

$mday
[1] 5

$mon
[1] 3

$year
[1] 118

$wday
[1] 4

$yday
[1] 94

$isdst
[1] 0

$zone
[1] "UTC"

$gmtoff
[1] NA

In [239]:
d3$mday<-6

In [240]:
d3

[1] "2018-04-06 UTC"

In [241]:
str(d3)

 POSIXlt[1:1], format: "2018-04-06"


In [242]:
c(as.POSIXct("2018-01-01"),as.POSIXct("2018-01-02"),as.POSIXct("2018-01-03"))

[1] "2018-01-01 UTC" "2018-01-02 UTC" "2018-01-03 UTC"

In [243]:
df<-data.frame(fecha=c(as.POSIXlt("2018-01-01"),as.POSIXlt("2018-01-02"),as.POSIXlt("2018-01-03")))
str(df)


'data.frame':	3 obs. of  1 variable:
 $ fecha: POSIXct, format: "2018-01-01" "2018-01-02" ...


## Valores infinitos y NaN (Not a Number)

Inf y -Inf son negativo positivo y negativo, mientras que NaN significa "Not a Number"

In [248]:
#x <- 10
#x <- 1/0
x <- 0/0
paste("El valor de x es",x)

is.finite(x)
is.infinite(x)
is.nan(x)

[1] "El valor de x es NaN"

[1] FALSE

[1] FALSE

[1] TRUE

In [249]:
#Valores NaN
is.nan(NaN)
is.nan(0/0)
is.nan(Inf-Inf)

[1] TRUE

[1] TRUE

[1] TRUE

La comprobación de si un número es NaN se tiene que realizar con la funcion is.nan()

In [250]:
x<-NaN
x==NaN
is.nan(x)

[1] NA

[1] TRUE

## Valores NULL

Simplemente son valores que no existen. Es un concepto similar a otros lenguajes como Java o C.

In [251]:
# Los valores NULL simplemente se ignoran
c(1,2,NA,NULL,3,NULL,3,NULL)

[1]  1  2 NA  3  3

In [252]:
x<-NULL
x
is.null(x)

NULL

[1] TRUE

In [253]:
df<-data.frame(x=c(1,2,1,1),y=c(3,2,1,1))
df

x y
1 1 3
2 2 2
3 1 1
4 1 1

In [254]:
df$y<- NULL
df

x
1 1
2 2
3 1
4 1

In [255]:
df$y
is.null(df$y)

NULL

[1] TRUE

In [257]:
df$MyCol
is.null(df$MyCol)

NULL

[1] TRUE

## Valores no disponibles / Missing Values

Son valores para los cuales no tenemos ninguna medida, se representan con un NA ("Not Available).

Pertenecen a valores perdidos que no se han podido recuperar, errores de medida, perdidas de datos, etc..

En R los detectamos con: *is.na(x)*

y podemos reemplazar su valor con la media, moda, mediana, etc...

o simplemente eliminarlos: *na.omit(x)*

Si estamos trabajando con series temporales es posible que queramos hacer una interpolación de los valores perdidos:

zoo::na.approx(x)

In [258]:
NA

[1] NA

In [259]:
data<-c(1,3,NA,6)
data

[1]  1  3 NA  6

In [260]:
is.na(data)

[1] FALSE FALSE  TRUE FALSE

In [261]:
na.omit(data)

[1] 1 3 6
attr(,"na.action")
[1] 3
attr(,"class")
[1] "omit"

In [262]:
paste("El número de elementos con NA:",length(data[is.na(data)]))

[1] "El número de elementos con NA: 1"

In [264]:
sum(is.na(data))

[1] 1

In [265]:
paste("El número de elementos que NO son NA:",length(data[!is.na(data)]))

[1] "El número de elementos que NO son NA: 3"

In [266]:
data[1]<-10
data

[1] 10  3 NA  6

In [267]:
data[is.na(data)] <- 28
data

[1] 10  3 28  6

## Ejemplo datos reales


#### Dataset coches

Partimos del dataset de seguro de automóviles que podemos descargar de:

https://archive.ics.uci.edu/ml/datasets/Automobile


In [268]:
autos<-read.csv("./data//imports-85.data", col.names = c("risk", "normalized_losses", 
                                                         "make", "fuel_type", "aspiration",
           "num_doors", "body_style", "drive_wheels", "engine_location",
           "wheel_base", "length", "width", "height", "curb_weight",
           "engine_type", "num_cylinders", "engine_size", "fuel_system",
           "bore", "stroke", "compression_ratio", "horsepower", "peak_rpm",
           "city_mpg", "highway_mpg", "price"))

In [269]:
str(autos)

'data.frame':	204 obs. of  26 variables:
 $ risk             : int  3 1 2 2 2 1 1 1 0 2 ...
 $ normalized_losses: chr  "?" "?" "164" "164" ...
 $ make             : chr  "alfa-romero" "alfa-romero" "audi" "audi" ...
 $ fuel_type        : chr  "gas" "gas" "gas" "gas" ...
 $ aspiration       : chr  "std" "std" "std" "std" ...
 $ num_doors        : chr  "two" "two" "four" "four" ...
 $ body_style       : chr  "convertible" "hatchback" "sedan" "sedan" ...
 $ drive_wheels     : chr  "rwd" "rwd" "fwd" "4wd" ...
 $ engine_location  : chr  "front" "front" "front" "front" ...
 $ wheel_base       : num  88.6 94.5 99.8 99.4 99.8 ...
 $ length           : num  169 171 177 177 177 ...
 $ width            : num  64.1 65.5 66.2 66.4 66.3 71.4 71.4 71.4 67.9 64.8 ...
 $ height           : num  48.8 52.4 54.3 54.3 53.1 55.7 55.7 55.9 52 54.3 ...
 $ curb_weight      : int  2548 2823 2337 2824 2507 2844 2954 3086 3053 2395 ...
 $ engine_type      : chr  "dohc" "ohcv" "ohc" "ohc" ...
 $ num_cylinders    :

In [272]:
tail(autos)

risk normalized_losses make  fuel_type aspiration num_doors body_style
199 -1   74                volvo gas       turbo      four      wagon     
200 -1   95                volvo gas       std        four      sedan     
201 -1   95                volvo gas       turbo      four      sedan     
202 -1   95                volvo gas       std        four      sedan     
203 -1   95                volvo diesel    turbo      four      sedan     
204 -1   95                volvo gas       turbo      four      sedan     
    drive_wheels engine_location wheel_base ⋯ engine_size fuel_system bore
199 rwd          front           104.3      ⋯ 130         mpfi        3.62
200 rwd          front           109.1      ⋯ 141         mpfi        3.78
201 rwd          front           109.1      ⋯ 141         mpfi        3.78
202 rwd          front           109.1      ⋯ 173         mpfi        3.58
203 rwd          front           109.1      ⋯ 145         idi         3.01
204 rwd          front           109.1      ⋯ 141         mpfi        3.78
    stroke compression_ratio horsepower peak_rpm city_mpg highway_mpg price
199 3.15    7.5              162        5100     17       22          18950
200 3.15    9.5              114        5400     23       28          16845
201 3.15    8.7              160        5300     19       25          19045
202 2.87    8.8              134        5500     18       23          21485
203 3.40   23.0              106        4800     26       27          22470
204 3.15    9.5              114        5400     19       25          22625

Nos quedamos solo con las columnas: "price","horsepower","body_style","risk"

In [277]:
# Para eliminar una sola columna
autos$fuel_type <- NULL

In [279]:
autos <- autos[,c('price','horsepower', 'body_style', 'risk' )]
head(autos)

price horsepower body_style  risk
1 16500 111        convertible 3   
2 16500 154        hatchback   1   
3 13950 102        sedan       2   
4 17450 115        sedan       2   
5 15250 110        sedan       2   
6 17710 110        sedan       1

En este CSV cuando existe un valor desconocido lo han indicado con el caracter '?'. Por ese motivo la columna 'price' y 'horsepower' es factor en lugar de numeric.
Tenemos que indicarle a R que son NA:

In [285]:
autos[autos$price == '?','price'] <- NA

In [288]:
autos$horsepower[autos$horsepower== '?'] <- NA

In [289]:
summary(autos)

    price            horsepower         body_style             risk        
 Length:204         Length:204         Length:204         Min.   :-2.0000  
 Class :character   Class :character   Class :character   1st Qu.: 0.0000  
 Mode  :character   Mode  :character   Mode  :character   Median : 1.0000  
                                                          Mean   : 0.8235  
                                                          3rd Qu.: 2.0000  
                                                          Max.   : 3.0000  

Tenemos que convertir el factor de 'price' y 'horsepower' en valores numéricos:

In [293]:
autos$horsepower <- as.numeric(autos$horsepower)
autos$price <- as.numeric(autos$price)

In [294]:
summary(autos)

     price         horsepower     body_style             risk        
 Min.   : 5118   Min.   : 48.0   Length:204         Min.   :-2.0000  
 1st Qu.: 7775   1st Qu.: 70.0   Class :character   1st Qu.: 0.0000  
 Median :10270   Median : 95.0   Mode  :character   Median : 1.0000  
 Mean   :13206   Mean   :104.2                      Mean   : 0.8235  
 3rd Qu.:16501   3rd Qu.:116.0                      3rd Qu.: 2.0000  
 Max.   :45400   Max.   :288.0                      Max.   : 3.0000  
 NA's   :4       NA's   :2                                           

¿Cuantos tipos de body_style hay?

In [295]:
unique(autos$body_style)

[1] "convertible" "hatchback"   "sedan"       "wagon"       "hardtop"

¿Cuantos elementos hay por cada valor de body_style?

In [296]:
table(autos$body_style)


convertible     hardtop   hatchback       sedan       wagon 
          5           8          70          96          25 

Convertimos la columna a factor:

In [297]:
autos$body_style <- as.factor(autos$body_style)
summary(autos)

     price         horsepower          body_style      risk        
 Min.   : 5118   Min.   : 48.0   convertible: 5   Min.   :-2.0000  
 1st Qu.: 7775   1st Qu.: 70.0   hardtop    : 8   1st Qu.: 0.0000  
 Median :10270   Median : 95.0   hatchback  :70   Median : 1.0000  
 Mean   :13206   Mean   :104.2   sedan      :96   Mean   : 0.8235  
 3rd Qu.:16501   3rd Qu.:116.0   wagon      :25   3rd Qu.: 2.0000  
 Max.   :45400   Max.   :288.0                    Max.   : 3.0000  
 NA's   :4       NA's   :2                                         

#### Dataset cancer esófago


Se realizó un estudio retrospectivo de casos y controles de 200 casos masculinos de cáncer de esófago y 778 controles poblacionales en Ille-et-Vilanine (Francia). Los logaritmos de los riesgos relativos de desarrollar la enfermedad aumentan linealmente con el consumo diario de alcohol y tabaco de manera independiente. El efecto combinado de ambos se ajusta con un modelo multiplicativo que se propone. Este modelo podría ser aplicable a otras situaciones. Explica la proporción de sexos y las diferencias urbanas / rurales observadas en Ille-er-Vilaine. 

http://www.math.umd.edu/~evs/s430.old/Data/ESOPH.dat

Columnas:
* agegp: grupo de edad
* alcgp: consumo de alcohol
* tobgp: consumo de tabaco
* ncases: número de casos de cancer
* ncontrol: población de control


In [304]:
dfcancer<-read.csv("data/ESOPH.dat",skip=43,sep = "", stringsAsFactors = T)
head(dfcancer)

agegp alcgp     tobgp    ncases ncontrols
1 25-34 0-39g/day 0-9g/day 0      40       
2 25-34 0-39g/day 10-19    0      10       
3 25-34 0-39g/day 20-29    0       6       
4 25-34 0-39g/day 30+      0       5       
5 25-34 40-79     0-9g/day 0      27       
6 25-34 40-79     10-19    0       7

In [305]:
str(dfcancer)

'data.frame':	88 obs. of  5 variables:
 $ agegp    : Factor w/ 6 levels "25-34","35-44",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ alcgp    : Factor w/ 4 levels "0-39g/day","120+",..: 1 1 1 1 3 3 3 3 4 4 ...
 $ tobgp    : Factor w/ 4 levels "0-9g/day","10-19",..: 1 2 3 4 1 2 3 4 1 2 ...
 $ ncases   : int  0 0 0 0 0 0 0 0 0 0 ...
 $ ncontrols: int  40 10 6 5 27 7 4 7 2 1 ...


In [306]:
summary(dfcancer)

   agegp          alcgp         tobgp        ncases         ncontrols    
 25-34:15   0-39g/day:23   0-9g/day:24   Min.   : 0.000   Min.   : 1.00  
 35-44:15   120+     :21   10-19   :24   1st Qu.: 0.000   1st Qu.: 3.00  
 45-54:16   40-79    :23   20-29   :20   Median : 1.000   Median : 6.00  
 55-64:16   80-119   :21   30+     :20   Mean   : 2.273   Mean   :11.08  
 65-74:15                                3rd Qu.: 4.000   3rd Qu.:14.00  
 75+  :11                                Max.   :17.000   Max.   :60.00  

En ocasiones podemos convertir los factores en números. Com en este caso que sustituimos los rangos por su valor medio:

In [307]:
unique(dfcancer$agegp)

[1] 25-34 35-44 45-54 55-64 65-74 75+  
Levels: 25-34 35-44 45-54 55-64 65-74 75+

In [308]:
levels(dfcancer$agegp)

[1] "25-34" "35-44" "45-54" "55-64" "65-74" "75+"

In [309]:
ageVectors <- c(30, 40, 50, 60, 70, 80)


In [314]:
ageVectors[c(1,4,1,2,1)]

[1] 30 60 30 40 30

In [313]:
as.numeric(dfcancer$agegp)

[1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3
[39] 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5
[77] 5 6 6 6 6 6 6 6 6 6 6 6

In [316]:
dfcancer$ageVectors <- ageVectors[as.numeric(dfcancer$agegp)]

In [317]:
summary(dfcancer)

   agegp          alcgp         tobgp        ncases         ncontrols    
 25-34:15   0-39g/day:23   0-9g/day:24   Min.   : 0.000   Min.   : 1.00  
 35-44:15   120+     :21   10-19   :24   1st Qu.: 0.000   1st Qu.: 3.00  
 45-54:16   40-79    :23   20-29   :20   Median : 1.000   Median : 6.00  
 55-64:16   80-119   :21   30+     :20   Mean   : 2.273   Mean   :11.08  
 65-74:15                                3rd Qu.: 4.000   3rd Qu.:14.00  
 75+  :11                                Max.   :17.000   Max.   :60.00  
   ageVectors   
 Min.   :30.00  
 1st Qu.:40.00  
 Median :50.00  
 Mean   :53.86  
 3rd Qu.:70.00  
 Max.   :80.00  

In [318]:
head(dfcancer)

agegp alcgp     tobgp    ncases ncontrols ageVectors
1 25-34 0-39g/day 0-9g/day 0      40        30        
2 25-34 0-39g/day 10-19    0      10        30        
3 25-34 0-39g/day 20-29    0       6        30        
4 25-34 0-39g/day 30+      0       5        30        
5 25-34 40-79     0-9g/day 0      27        30        
6 25-34 40-79     10-19    0       7        30